name: Construir, Enviar e Implantar VMPay Backend

on:
  push:
    branches: [main]

env:
  AWS_REGION: sa-east-1
  ECR_REPOSITORY: vmpay-image-repo
  IMAGE_TAG: prod
  DEPLOY_HOST: srv844980.hstgr.cloud
  DEPLOY_USER: github
  SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  ENV_FILE_PATH: /home/github/sistemas/vmpay/env

jobs:
  construir:
    name: Construir e Enviar para ECR
    runs-on: ubuntu-latest
    outputs:
      image_uri: ${{ steps.build-image.outputs.image }}
      ecr_registry: ${{ steps.login-ecr.outputs.registry }}

    steps:
      - name: Fazer checkout do repositório
        uses: actions/checkout@v5

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Fazer login no Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Construir, marcar e enviar imagem para Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.IMAGE_TAG }} .
          echo "Enviando imagem para ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.IMAGE_TAG }}
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:${{ env.IMAGE_TAG }}" >> $GITHUB_OUTPUT

  implantar:
    name: Implantar no Servidor de Produção
    runs-on: ubuntu-latest
    needs: construir

    steps:
      - name: Deploy via SSH (appleboy)
        uses: appleboy/ssh-action@v1.2.2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ env.AWS_REGION }}
        with:
          host: ${{ env.DEPLOY_HOST }}
          username: ${{ env.DEPLOY_USER }}
          key: ${{ env.SSH_KEY }}
          envs: AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,AWS_REGION
          script: |
            IMAGE_URI="${{ needs.construir.outputs.image_uri }}"
            ECR_REGISTRY="${{ needs.construir.outputs.ecr_registry }}"
            ENV_FILE_PATH="${{ env.ENV_FILE_PATH }}"

            echo "Fazendo login no ECR: $ECR_REGISTRY"
            aws ecr get-login-password --region sa-east-1 --profile vmpay | docker login --username AWS --password-stdin 769998260029.dkr.ecr.sa-east-1.amazonaws.com
            echo "Baixando imagem: $IMAGE_URI"
            docker pull "$IMAGE_URI"

            docker stop vmpay || true
            docker rm vmpay || true

            docker run -d \
            --name vmpay \
            --network reverse-proxy_caddy_net \
            --restart unless-stopped \
            --env-file "$ENV_FILE_PATH" \
            "$IMAGE_URI"
